# from hvr's multi-ghc-travis template

env:
 - GHCVER=7.6.1
 - GHCVER=7.6.3

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update
 - sudo apt-get install libzmq3-dev freeglut3-dev liblapack-dev libblas-dev libgsl0-dev llvm
 - sudo apt-get install cabal-install-1.18 ghc-$GHCVER happy
 - sudo apt-get install git
 - sudo apt-get install freeglut3-dev liblapack-dev libblas-dev libgsl0-dev llvm
 - export PATH=/opt/ghc/$GHCVER/bin:$PATH
 - git clone http://github.com/ImAlsoGreg/haskell-tetrode-ephys

install:
 - cabal-1.18 update

script:
 - cabal-1.18 sandbox init
 - git clone https://github.com/ImAlsoGreg/tetrode-ephys.git
 - cabal-1.18 sandbox add-source tetrode-ephys
 - cabal-1.18 install --only-dependencies --enable-tests --enable-benchmarks
 - cabal-1.18 configure
 - cabal-1.18 build
 - cabal-1.18 install
